RIA-3088 Legal rep submits appeal with a remission
hmcts/ia-ccd-e2e-tests pull request #335
Opened 2020-10-20 10:07 UTC by tarun-palisetty

### JIRA link (if applicable) ###
[RIA-3088](https://tools.hmcts.net/jira/browse/RIA-3088)

### Change description ###
Legal rep submits appeal with a remission

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-10-27 12:43 UTC, Lee365 requested changes
minor typo

2020-10-27 12:43 UTC, Lee365 commented on e2e/features/submit-appeal-with-resmission.feature
> +Feature: Submit appeal with has a remission
Filename type needs to be corrected to remission

2020-11-12 16:53 UTC, Srihari-Nakkala approved these changes
LGTM

2020-11-23 12:16 UTC, Lee365 approved these changes

2020-11-24 10:11 UTC, merged