RIA-3218 Legal rep apply for a late remission
hmcts/ia-ccd-e2e-tests pull request #365
Opened 2020-12-11 08:04 UTC by tarun-palisetty

### JIRA link (if applicable) ###
[RIA-3218](https://tools.hmcts.net/jira/browse/RIA-3218)

### Change description ###
Legal rep apply for a late remission

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-12-14 12:58 UTC, divisathyan requested changes
One small typo change

2020-12-14 12:58 UTC, divisathyan commented on e2e/features/apply-for-late-remission.feature
> +    And I should see the text `view in the appeal tab when the decision has bee made.`
Typo for "has been made"

2020-12-17 12:13 UTC, tarun-palisetty commented on e2e/features/apply-for-late-remission.feature
> +    And I should see the text `view in the appeal tab when the decision has bee made.`
Fixed the typo

2020-12-17 17:10 UTC, Srihari-Nakkala approved these changes
LGTM

2021-02-26 09:37 UTC, makowalski submitted a review, later dismissed
LGTM

2021-04-06 13:39 UTC, makowalski approved these changes
LGTM

2021-04-06 13:41 UTC, divisathyan approved these changes

2021-04-06 14:07 UTC, merged