RIA-3882 Admin officer journey chooses fee update not required after additional fee required
hmcts/ia-ccd-e2e-tests pull request #379
Opened 2021-01-07 15:37 UTC by tarun-palisetty

### JIRA link (if applicable) ###
[RIA-3882](https://tools.hmcts.net/jira/browse/RIA-3882)

### Change description ###
Admin officer journey chooses fee update not required after additional fee required

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-01-08 14:43 UTC, divisathyan requested changes
Please see comment

2021-01-08 14:43 UTC, divisathyan commented on e2e/features/manage-fee-update.feature
> +
Missing confirmation page check

2021-01-08 14:43 UTC, divisathyan commented on e2e/features/manage-fee-update.feature
> +    And I type `10` for the `New fee amount (£)` field
Remove the (£) for New amount

2021-01-08 14:43 UTC, divisathyan commented on e2e/features/manage-fee-update.feature
> +    And I should see `£10.00` in the `New fee amount (£)` field
same as above

2021-01-19 13:34 UTC, tarun-palisetty commented on e2e/features/manage-fee-update.feature
> +    And I type `10` for the `New fee amount (£)` field
Removed the £ sign

2021-01-19 13:34 UTC, tarun-palisetty commented on e2e/features/manage-fee-update.feature
> +    And I should see `£10.00` in the `New fee amount (£)` field
removed

2021-01-19 13:38 UTC, tarun-palisetty commented on e2e/features/manage-fee-update.feature
> +
Added the check

2021-01-19 14:21 UTC, Srihari-Nakkala submitted a review, later dismissed
LGTM

2021-04-16 11:23 UTC, divisathyan approved these changes

2021-04-16 11:28 UTC, merged