RIA-3876:Out of country screening questions
hmcts/ia-ccd-e2e-tests pull request #387
Opened 2021-01-19 17:47 UTC by mkayad

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-2110

### Change description ###
see ticket

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-01-21 16:57 UTC, Lee365 requested changes

2021-01-21 16:57 UTC, Lee365 commented on e2e/features/stepDefinitions/ccd-page.steps.ts
> +        'Appeal* RIA-2110'
This need to be reverted.

2021-01-22 09:01 UTC, mkayad commented on e2e/features/stepDefinitions/ccd-page.steps.ts
> +        'Appeal* RIA-2110'
changed to master

2021-01-22 12:09 UTC, Lee365 approved these changes
LGTM

2021-01-27 10:46 UTC, Srihari-Nakkala commented on e2e/features/start-appeal-out-of-country-no-sponsor.feature
> +
@mkayad This Test won't work with when we switch ON F&P Flag, AC is covering F&P scenarios as well and Not 
sure why we are not submitting appeal as part of this Tests.

2021-01-27 10:47 UTC, Srihari-Nakkala commented on e2e/features/start-appeal-out-of-country-no-sponsor.feature
> +
Same Here @mkayad

2021-01-29 21:05 UTC, Lee365 submitted a review, later dismissed
LGTM

2021-02-04 18:35 UTC, Srihari-Nakkala approved these changes
LGTM

2021-02-26 11:04 UTC, Lee365 approved these changes
LGTM

2021-02-26 12:46 UTC, merged