Ria 3877 ooc
hmcts/ia-ccd-e2e-tests pull request #391
Opened 2021-01-25 15:46 UTC by mkayad

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3877

### Change description ###
See ticket

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2021-01-26 17:26 UTC, Lee365 requested changes

2021-01-26 17:26 UTC, Lee365 commented on e2e/features/start-appeal-out-of-country-removal-of-client.feature
> +Feature: Out of country appeal removal of client
"I save my initial appeal" journey to include ooc journey with check on IA_OUT_OF_COUNTRY_ENABLED

2021-01-29 21:23 UTC, Lee365 approved these changes
LGTM

2021-02-10 13:54 UTC, Srihari-Nakkala submitted a review, later dismissed
LGTM

2021-02-26 13:15 UTC, Lee365 approved these changes
LGTM

2021-03-01 09:27 UTC, merged